"""Correction

Revision ID: 6622d3e04419
Revises: 9aa5790afbb3
Create Date: 2024-11-22 21:40:29.376753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6622d3e04419'
down_revision = '9aa5790afbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idCategory', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['idCategory'], ['idCategory'])
        batch_op.drop_column('idcategory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idcategory', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idCategory')

    # ### end Alembic commands ###
