"""primera migraciones

Revision ID: 6fa5f5f2a403
Revises: 
Create Date: 2024-11-26 21:29:32.465772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa5f5f2a403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('idLevel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idLevel')
    )
    op.create_table('users',
    sa.Column('idUser', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCard', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=50), nullable=False),
    sa.Column('surnames', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('idCard')
    )
    op.create_table('monsters',
    sa.Column('idMonsters', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idLevel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['idLevel'], ['level.idLevel'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idMonsters')
    )
    op.create_table('categories',
    sa.Column('idCategory', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idMonsters', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=65), nullable=False),
    sa.ForeignKeyConstraint(['idMonsters'], ['monsters.idMonsters'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idCategory')
    )
    op.create_table('game',
    sa.Column('idGame', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idMonsters', sa.Integer(), nullable=True),
    sa.Column('idLevel', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('finalScore', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idLevel'], ['level.idLevel'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idMonsters'], ['monsters.idMonsters'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idGame')
    )
    op.create_table('questions',
    sa.Column('idQuestion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['idCategory'], ['categories.idCategory'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idQuestion')
    )
    op.create_table('answers',
    sa.Column('idAnswer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idQuestion', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=170), nullable=False),
    sa.Column('isCorrect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idQuestion'], ['questions.idQuestion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAnswer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('game')
    op.drop_table('categories')
    op.drop_table('monsters')
    op.drop_table('users')
    op.drop_table('level')
    # ### end Alembic commands ###
