"""karen

Revision ID: 8165147b9bb7
Revises: 1c211c31565b
Create Date: 2024-11-20 17:16:29.391338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8165147b9bb7'
down_revision = '1c211c31565b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('idLevel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idLevel')
    )
    op.create_table('answers',
    sa.Column('idAnswer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idQuestion', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=170), nullable=False),
    sa.Column('isCorrect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idQuestion'], ['questions.idQuestion'], ),
    sa.PrimaryKeyConstraint('idAnswer')
    )
    op.create_table('game',
    sa.Column('idGame', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('finalScore', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('idGame')
    )
    op.create_table('monsters',
    sa.Column('idMonsters', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idLevel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['idLevel'], ['level.idLevel'], ),
    sa.PrimaryKeyConstraint('idMonsters')
    )
    op.create_table('categories',
    sa.Column('idCategory', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idMonsters', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=65), nullable=False),
    sa.ForeignKeyConstraint(['idMonsters'], ['monsters.idMonsters'], ),
    sa.PrimaryKeyConstraint('idCategory')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('monsters')
    op.drop_table('game')
    op.drop_table('answers')
    op.drop_table('level')
    # ### end Alembic commands ###
