"""karen2

Revision ID: 9aa5790afbb3
Revises: 8165147b9bb7
Create Date: 2024-11-20 17:22:50.360398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa5790afbb3'
down_revision = '8165147b9bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_has_level',
    sa.Column('idGameHasLevel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idGame', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idLevel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idGame'], ['game.idGame'], ),
    sa.ForeignKeyConstraint(['idLevel'], ['level.idLevel'], ),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('idGameHasLevel')
    )
    op.create_table('game_has_monsters',
    sa.Column('idGameHasMonsters', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idGame', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idMonsters', sa.Integer(), nullable=False),
    sa.Column('idLevel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idGame'], ['game.idGame'], ),
    sa.ForeignKeyConstraint(['idLevel'], ['level.idLevel'], ),
    sa.ForeignKeyConstraint(['idMonsters'], ['monsters.idMonsters'], ),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('idGameHasMonsters')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_has_monsters')
    op.drop_table('game_has_level')
    # ### end Alembic commands ###
